### ISSUE TITLE
CMake cache vars are missing project name prefix

### ISSUE THREAD

**Issue by globberwops** [eclipse-ecal/ecal-core#6]
**Describe the bug**
Some CMake cache vars are missing a project specific prefix.
This can lead to problems when eCAL is added to another project via `add_subdirectory` e.g. via `FetchContent`.
In addition, using a common prefix for all cache vars will cluster them nicely in CMake GUI.

**Expected behavior**
All CMake cache vars have a common prefix.

**Desktop (please complete the following information):**
Not applicable

**Comment by FlorianReimold** [comment]
I totally agree with this PR. The ecal-core standalone project is currently still work in progress however and we keep it compatible with the main eCAL Repo, which is why I don't want to merge the PR, yet.

In a branch I even went a bit further and prefixed everything with `ECAL_CORE_COMPONENT_*`, `ECAL_CORE_THIRDPARTY_*` etc.
https://github.com/eclipse-ecal/ecal-core/blob/847e13c9d9a721dacd13ecd415139948671d54a7/CMakeLists.txt#L85

We will get to  this! 😊

**Comment by rex-schilasky** [comment]
Done
